# Generated by Django 4.1.7 on 2023-03-01 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=256, verbose_name='Name')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
                ('categories', models.ManyToManyField(help_text='Related categories', to='api.category')),
            ],
            options={
                'ordering': ['name', 'brand'],
            },
        ),
    ]
