# Generated by Django 4.1.7 on 2023-03-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_brand_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Related categories', related_name='products', to='api.category'),
        ),
    ]
